### ISSUE TITLE
Documentation not compatible with M11.0 or earlier

### ISSUE THREAD

**Issue by szhorvat** [WolframResearch/GitLink#10]
The documentation is not compatible with Mathematica 11.0 or earlier.

See screenshot:

![image](https://user-images.githubusercontent.com/1212871/55864171-3b459900-5b7c-11e9-9e17-7e7722c21af1.png)

**Comment by jfultz** [comment]
I've already updated the Readme to indicate compatibility is with 11.1 or later.
