### ISSUE TITLE
Marked as compatible with M10.1 but uses M10.2 symbols

### ISSUE THREAD

**Issue by szhorvat** [WolframResearch/GitLink#11]
The package is marked as compatible with Mathematica 10.1+ in PacletInfo, but some functions use the symbol `Nothing`, which requires M10.2.

https://github.com/WolframResearch/GitLink/blob/master/GitLink/Kernel/GitLink.wl#L1253

**Comment by szhorvat** [comment]
OK, now I see that the README says 11.1 is required. Thus the last three issues should all be replaced with "update PacletInfo to require 11.1".

**Comment by jfultz** [comment]
Fixed in fc62ef6070f0.
