### ISSUE TITLE
GitLink won't show up in list of installed add-ons

### ISSUE THREAD

**Issue by szhorvat** [WolframResearch/GitLink#2]
GitLink won't show up in the list of installed add-ons. I don't know whether this is intentional and what causes it.

![image](https://cloud.githubusercontent.com/assets/1212871/20433912/e3f6d6b8-ada5-11e6-9a8f-dab227784e34.png)

I can find its documentation by searching.

**Comment by jfultz** [comment]
Ultimately GitLink will be a built-in system paclet, so no, it shouldn't show up here.

**Comment by szhorvat** [comment]
Out of curiosity, is this achieved by `Internal -> True`?  Trying that on a different package didn't have the effect of removing if from the list of add-ons on the documentation center.
