### ISSUE TITLE
support for ranges

### ISSUE THREAD

**Issue by kubaPod** [WolframResearch/GitLink#4]
Does GitRange, ToGitObject etc support [ranges](http://schacon.github.io/git/git-rev-parse#_specifying_revisions)?

e.g. GitRange[repo, "hash1..hash2"] 
or GitRange[repo, "^hash1 hash2"] 

fail. I end up with ridiculous solution:

Complement[
 GitRange[repo, ToGitObject[repo, "hash2"]],
 GitRange[repo, ToGitObject[repo, "hash1"]]
]

**Comment by jfultz** [comment]
As the documentation for `GitRange` says:

> The common git command-line specification of ref1..ref2 is equivalent to `GitRange[repo,Except["ref1"],"ref2"]`.

**Comment by kubaPod** [comment]
Indeed, somehow I assumed GitLink does not have documentation. Embarrassing. Thanks.

**Comment by jfultz** [comment]
If you're using GitLink from an 11.2 beta, you might not be finding documentation because of a bug in the beta.  You can direct hit the documentation by doing, e.g., `GitLink/ref/GitRange`, but typing `GitRange` by itself doesn't work.  This should be fixed for the final 11.2 release.

**Comment by szhorvat** [comment]
That problem with documentation search is described here:

https://mathematica.stackexchange.com/questions/155717/pop-up-appeared-and-then-disappeared-during-first-documentation-search-in-11-2

The GitLink doc search did indeed work fine in 11.2 final (reindexing was triggered after a restart + frist search).

**Comment by kubaPod** [comment]
I think that explains my confusion, at least I will stick to this excuse.
