### ISSUE TITLE
Usage of CommitterSignature and AuthorSignature

### ISSUE THREAD

**Issue by kubaPod** [WolframResearch/GitLink#6]
Either there is a problem with those options or we use it incorrectly. In the latter case the issue would only be about clarifying the usage in documentation.

Shortly, they either break `GitCommit` or have no effect at all. More in:

https://mathematica.stackexchange.com/q/163753/5478

**Comment by jfultz** [comment]
There are two problems here.
1) There's a bug in the WL code for `GitCommit` which causes it to mishandle the option if you specify anything less than the 4-argument form.
2) There was a mis-usage in the examples on SE...you must specify a complete signature, like the one that is returned from `GitSignature[]`, and this includes the `"TimeStamp"` member.  However, `"TimeStamp"` takes a `DateObject` and, unbeknownst to me, the fullform of `DateObject` changed in recent releases of WL.  The C++ code that reads the `DateObject` into the signature is looking for the now-legacy form.

I have a fix for the first already, and the second isn't hard, so should be coming soon.

**Comment by jfultz** [comment]
Problems fixed, unit tests added in fc62ef6070f0 and e10598b9869a.
