### ISSUE TITLE
Does not work with M10.3 on OS X

### ISSUE THREAD

**Issue by szhorvat** [WolframResearch/GitLink#9]
The latest release (2018.07.20.01) does not include binaries for M10.3 on macOS, so when I try to load it, I get

```
<< GitLink`

InitializeGitLibrary::libnotfound: -- Message text not found --
```

**Comment by jfultz** [comment]
ReadMe already indicates that minimum version should be 11.1.  Maintaining the build for the older `libstdc++` version of MathLink required for pre-10.3 compatibility is becoming increasingly difficult due to the aggressive deprecation by Apple.
